[package]
name = "heyrnode"
version = "0.1.0"
edition = "2024"

[features]
default = []
tokio = [
  "dep:futures-util",
  "dep:tokio",
  "dep:tokio-stream",
]

[dependencies]
futures-util = { version = "0.3.34", optional = true, default-features = false }
serialport = "4.9.0"
tokio = { version = "1.53.1", optional = true, features = ["rt", "sync"] }
tokio-stream = { version = "0.1.19", optional = true, default-features = false, features = ["sync"] }
tracing = "0.1.44"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
