[package]
name = "heyrnode"
version = "0.1.0"
edition = "2024"
authors = [
  "adz <x12@adz.garden>",
]
description = "Client to interface with RNode hardware via serial port"
repository = "https://github.com/adzialocha/heyrnode"
license = "MIT"
readme = "README.md"

[features]
default = []
tokio = [
  "dep:futures-util",
  "dep:tokio",
  "dep:tokio-stream",
]

[dependencies]
bytes = "1.12.1"
futures-util = { version = "0.3.34", optional = true, default-features = false }
serialport = "4.10.0"
tokio = { version = "1.53.1", optional = true, features = ["sync"] }
tokio-stream = { version = "0.1.19", optional = true, default-features = false, features = ["sync"] }
tracing = "0.1.44"

[dev-dependencies]
heyrnode = { path = ".", features = ["tokio"] }
tokio = { version = "1.53.1", features = ["rt", "macros"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
